### ISSUE TITLE
Errors when using repeat masker 

### ISSUE THREAD

**Issue by mokhouja** [Dr-TSteimle/sv-finder#2]
Hi,
I've tried running the new version of sv-finder using repeat masker files from ucsc (as recommended) for hg38 but I am getting an error that the BGZF header is invalid:
```
thread 'main' panicked at src/main.rs:371:27:
called `Result::unwrap()` on an `Err` value: invalid BGZF header

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: sv_finder::main
   2: std::sys::backtrace::__rust_begin_short_backtrace
   3: std::rt::lang_start::{{closure}}
   4: std::rt::lang_start_internal
   5: main
   6: __libc_start_call_main
   7: __libc_start_main@GLIBC_2.2.5
   8: _start
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: sv_finder::main
```

Have you encountered similar problems?

Thanks in advance!
Mouhamad

**Comment by Dr-TSteimle** [comment]
Hey Mouhamad! 👋

I've taken a look at the issue you're experiencing, and I think I might have spotted what's causing the error. It seems the repeat file you're working with is likely saved in gzip format rather than bgzip. 

Here's what I'd suggest to get things running smoothly:

1. First, uncompress the file to its original state.
2. Then, recompress it using bgzip, which is the format required.

```
mv rmsk.txt.gz rmsk_old.txt.gz
gunzip -c rmsk_old.txt.gz | bgzip > rmsk.txt.gz
```

If you don't have bgzip installed, you can usually get it by installing the htslib package:

```
sudo apt-get install htslib-tools # For Ubuntu/Debian
```

Let me know if you run into any problem during this process.

Best
Thomas

**Comment by mokhouja** [comment]
Hey Thomas,
Thank you for the rapid response! Indeed, this helped solving the problem! The output looks much better now!

Bests, Mouhamad
